import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Chats from "../../widgets/Chats";
import Bienvenido from "../../widgets/Bienvenido";
import Messages from "../../widgets/Messages";
import { useState } from "react";

const Chat = () => {
  const [open, setOpen] = useState(false);

  return (
    <div className={styles.fondo}>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/NoMessages.png" />
      </Head>
      <div className={styles.contenedorPrincipal}>
        <div className={styles.Wrapper}>
          <div className={styles.Contenido}>
            <div className={styles.InformacionChat}>
              <Chats setOpen={setOpen} />
              <div className={styles.contenedorBienvenido}>
                {open ? <Messages /> : <Bienvenido />}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Chat;
