import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Chats from "../../widgets/Chats";

const Chat = () => {
  return (
    <div className={styles.fondo}>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/NoMessages.png" />
      </Head>
      <div className={styles.contenedorPrincipal}>
        <div className={styles.Wrapper}>
          <div className={styles.Contenido}>
            <div className={styles.Informacion}>
                <Chats/>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Chat;
