import Head from "next/head";
import styles from "../styles/Home.module.css";
import Bienvenido from "../widgets/Bienvenido";
import Login from "../widgets/Login";

export default function Home() {
  return (
    <div className={styles.fondo}>
      <Head>
        <title>Entrevista</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/NoMessages.png" />
      </Head>
      <div className={styles.contenedorPrincipal}>
        <div className={styles.Wrapper}>
          <div className={styles.Contenido}>
            <div className={styles.Informacion}>
              <Login/>
              <Bienvenido/>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
